[package]
name = "cdi-alert-engine"
version = "0.1.0"
edition = "2021"
default-run = "cdi-alert-engine"

[dependencies]
bson = { version = "2.9.0", features = ["chrono-0_4", "serde_with-3"] }
chrono = "0.4.37"
mongodb = { version = "2.8.2", features = ["tokio-runtime"] }
serde = { version = "1.0.197", features = ["derive", "rc"] }
serde_with = "3.7.0"
tokio = { version = "1.37.0", features = ["full"] }
tracing = "0.1.40"
futures = "0.3.28"
thiserror = "1.0.58"
tracing-subscriber = "0.3.18"
mlua = { version = "0.9.6", features = ["luajit", "vendored", "async", "serialize"] }
toml = "0.8.12"
derive_environment = "1.1.0"
alua = "0.1.0"
clap = { version = "4.5.4", features = ["derive"] }
puffin = { version = "0.19.0", optional = true }
puffin_http = { version = "0.16.0", optional = true }
profiling = "1.0.15"
tracy-client = { version = "0.17.0", optional = true }

[features]
puffin = ["dep:puffin", "dep:puffin_http", "profiling/profile-with-puffin"]
tracy = ["dep:tracy-client", "profiling/profile-with-tracy"]
