[package]
name = "cdi-alert-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
ansi_term = "0.12.1"
bson = { version = "2.9.0", features = ["chrono-0_4", "serde_with-3"] }
chrono = "0.4.37"
itertools = "0.12.1"
lazy_static = "1.4.0"
mongodb = { version = "2.8.2", features = ["tokio-runtime"] }
serde = { version = "1.0.197", features = ["derive", "rc"] }
serde_json = "1.0.115"
serde_with = "3.7.0"
erased-serde = "0.4.0-rc.1"
tokio = { version = "1.37.0", features = ["full"] }
tracing = "0.1.40"
futures = "0.3.28"
thiserror = "1.0.58"
tracing-subscriber = "0.3.18"
mlua = { version = "0.9.6", features = ["luajit", "vendored", "async", "serialize"] }
toml = "0.8.12"

