polling_seconds = 5
create_test_data = true 
logging_level = "trace"

[mongo]
url = "mongodb://dolbeyadmin:fusion@dockermain:27032/admin"

[cdi_workgroup]
category = "CDI Alerts"
name = "CDI Alerts"

[[scripts]]
path = "scripts/test.lua"
criteria_group = "test"
