mongo_url = "mongodb://dolbeyadmin:fusion@dockermain:27032/admin"
cdi_workgroup_category = "CDI Alerts"
cdi_workgroup_name = "CDI Alerts"
polling_seconds = 5
create_test_data = true 

[lua]
scripts = "scripts/"
