polling_seconds = 5
create_test_data = true 
logging_level = "trace"

[mongo]
url = "mongodb://dolbeyadmin:fusion@dockermain:27032/admin"

[[scripts]]
path = "scripts/substance_abuse.lua"
criteria_group = "Substance Abuse"

[[scripts]] 
path = "scripts/atrial_fibrillation.lua"
criteria_group = "Atrial Fibrillation"

[[scripts]] 
path = "scripts/abnormal_serum_calcium.lua"
criteria_group = "Abnormal Serum Calcium"

[[scripts]] 
path = "scripts/abnormal_serum_potassium.lua"
criteria_group = "Abnormal Serum Potassium"

[[scripts]] 
path = "scripts/abnormal_serum_sodium.lua"
criteria_group = "Abnormal Serum Sodium"

[[scripts]] 
path = "scripts/acidosis.lua"
criteria_group = "Acidosis"

[[scripts]] 
path = "scripts/anemia.lua"
criteria_group = "Anemia"

[[scripts]] 
path = "scripts/acute_mi_troponemia.lua"
criteria_group = "Acute MI Troponemia"

